source 'https://github.com/CocoaPods/Specs.git'

target 'ILLibrary', :exclusive => true do
  pod "ILLibrary", :path => "../"
  pod 'FontAwesomeKit/FontAwesome'
  pod 'AFNetworking'
end

target 'Tests', :exclusive => true do
  pod "ILLibrary", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
